### ISSUE TITLE
Zero2W验证安装时报错

### ISSUE THREAD

**Issue by MoonLight423** [orangepi-xunlong/wiringOP-Python#26]
型号：Zero 2W 2GB
镜像：Orangepizero2w_1.0.0_ubuntu_jammy_desktop_xfce_linux6.1.31

根据教程进行安装
`sudo python3 setup.py install`
执行后的最终的输出信息
`Installed /usr/local/lib/python3.10/dist-packages/wiringpi-2.60.1-py3.10-linux-aarch64.egg`
`Processing dependencies for wiringpi==2.60.1`
`Finished processing dependencies for wiringpi==2.60.1`
验证安装时输出如下
`root@orangepizero2w:/home/orangepi/Downloads/wiringOP-Python# python3 -c "import wiringpi; help(wiringpi)"`
`Traceback (most recent call last):`
`  File "<string>", line 1, in <module>`
`  File "/home/orangepi/Downloads/wiringOP-Python/wiringpi.py", line 15, in <module>`
`    import _wiringpi`
`ImportError: /usr/local/lib/python3.10/dist-packages/wiringpi-2.60.1-py3.10-linux-aarch64.egg/_wiringpi.cpython-310-aarch64-linux-gnu.so: undefined symbol: sunxi_pwm_set_clk`

**Comment by arkylin** [comment]
可以试试 [ISSUE 25](https://github.com/orangepi-xunlong/wiringOP-Python/issues/25) 的解决方案

我也是2w，仅仅修改了下面这个就可以成功运行了

modify the bindings.i and replace the line: extern void sunxi_pwm_set_clk(int pin,int clk); to extern void sunxi_pwm_set_clk_v2(int pin,int clk); (just add the "_v2").

build again:

sudo python3 setup.py clean --all
sudo python3 setup.py build
sudo python3 setup.py install
