### ISSUE TITLE
WiringOP-Python don't work on Orangepi 5 Plus   ubuntu 22.04 , ubuntu 24.04

### ISSUE THREAD

**Issue by DanilSemen** [orangepi-xunlong/wiringOP-Python#27]
**Hello!!
WiringOP-Python don't work on Orangepi 5 Plus   ubuntu 22.04 , ubuntu 24.04
WiringOP-Python has stopped working in the last half a year.
sudo gpioreadall - ok
sudo python3 import wiringpi help  - ok**

**but**

"wiringpi.wiringpisetup "

 **given error** 
      **1) if I use the current version WiringOP-Python, given error**

orangepi@orangepi5plus:~ $ sudo -i
[sudo] password for orangepi: 
root@orangepi5plus:~ # python3
Python 3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import wiringpi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/wiringpi-2.60.1-py3.10-linux-aarch64.egg/wiringpi.py", line 15, in <module>
    import _wiringpi
ImportError: /usr/local/lib/python3.10/dist-packages/wiringpi-2.60.1-py3.10-linux-aarch64.egg/_wiringpi.cpython-310-aarch64-linux-gnu.so: undefined symbol: sunxi_pwm_set_clk
>>>

**if I use old archives from git,  given error** 
"wiringpisetup: mmap (gpio) failed: operation not permitted"

**and if i doing**

 "echo "BOARD=orangepi5" | sudo tee /etc/orangepi-release"
 "wiringpi.wiringpisetup " - ok , but pin only 26. my  board Orangeoi 5 plus with 40 pin.
 
 **if i doing** 
 
  "echo "BOARD=orangepi5plus" | sudo tee /etc/orangepi-release" 
  
   "wiringpi.wiringpisetup " -> error "wiringpisetup: mmap (gpio) failed: operation not permitted"
   
   **What happening????????**

**Comment by mag1art** [comment]
can you try reinstall python3.10 and wiringpi, then try run again?

**Comment by DanilSemen** [comment]
> can you try reinstall python3.10 and wiringpi, then try run again?

Its dont work
