### ISSUE TITLE
ModuleNotFoundError: No module named '_wiringpi‘

### ISSUE THREAD

**Issue by Huirong-Huang** [orangepi-xunlong/wiringOP-Python#28]
(yolo_py310) orangepi@orangepi5pro:/usr/src/wiringOP-Python$ python -c "import wiringpi; help(wiringpi)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/src/wiringOP-Python/wiringpi.py", line 15, in <module>
    import _wiringpi
ModuleNotFoundError: No module named '_wiringpi'

**Comment by Huirong-Huang** [comment]
sudo
